# Generated by Django 5.0.6 on 2024-06-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='amount',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=12),
        ),
    ]
