# Generated by Django 5.0.6 on 2024-06-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_deposite_amount_alter_userbankaccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
