# Generated by Django 5.0.6 on 2024-06-28 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ['borrow_date']},
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='borrowed_date',
            new_name='borrow_date',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='returned_date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_text',
        ),
        migrations.AddField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.CharField(default=1, max_length=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Borrow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000000)),
                ('image', models.ImageField(upload_to='image/uploads')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ManyToManyField(blank=True, null=True, to='Books.category')),
            ],
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Borrow', to='Books.bookmodel'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Books.bookmodel'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
