# Generated by Django 5.0.6 on 2024-06-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_alter_borrow_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={},
        ),
    ]
