# Generated by Django 5.0.6 on 2024-06-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_alter_borrow_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ['borrow_date']},
        ),
    ]
