# Generated by Django 5.0.6 on 2024-07-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0009_bookmodel_description_remove_bookmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='is_returend',
            field=models.BooleanField(default=False),
        ),
    ]
