# Generated by Django 5.0.6 on 2024-07-01 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0010_borrow_is_returend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='is_returend',
        ),
    ]
