# Generated by Django 5.0.6 on 2024-07-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0012_alter_bookmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='description',
            field=models.CharField(max_length=100000),
        ),
    ]
